version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"

  flask:
    image: flaskapp:latest
    container_name: flask-app
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DB: flaskdb
