name: Flask Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest .

      # 4️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest

      # 5️⃣ Deploy on remote server via SSH
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 1025
          script: |
            cd /root/downloads/two-tier-flask-app
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest
            docker stop flaskapp || true
            docker rm flaskapp || true
            docker run -d --name flaskapp -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest
